apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: openshift-gitops-operator
spec:
  project: default
  source:
    repoURL: https://github.com/kanekoh/standrized-cluster.git
    targetRevision: main
    path: apps
  destination:
    namespace: openshift-gitops-operator
    server: https://kubernetes.default.svc