apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kmm
  namespace: openshift-kmm
spec:
  channel: "stable"
  installPlanApproval: Automatic
  name: kernel-module-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace