apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcg
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://github.com/kanekoh/standrized-cluster.git
    targetRevision: main
    path: mcg/overlays/rhdp
  destination:
    namespace: openshift-gitops-operator
    server: https://kubernetes.default.svc