apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/kanekoh/standrized-cluster.git
    targetRevision: main
    path: logging/overlays/rhdp
  destination:
    namespace: openshift-gitops-operator
    server: https://kubernetes.default.svc