apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: nvidia-gpu-operator
spec:
  components: {}
  server:
    customCheProperties:
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: '-1'
  containerRegistry: {}
  devEnvironments: {}
  gitServices: {}
  networking: {}