apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: noobaa
  namespace: openshift-storage
spec:
 dbResources:
   requests:
     cpu: '100m'
     memory: 100Mi
 dbType: postgres
 coreResources:
   requests:
     cpu: '100m'
     memory: 100Mi
  endpoints:
    maxCount: 1
      requests:
        cpu: 100m
        memory: 100Mi