apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
  name: obc2secret
  namespace: openshift-logging
spec:
  parallelism: 1    
  completions: 1    
  activeDeadlineSeconds: 1800 
  backoffLimit: 6   
  template:         
    metadata:
      name: obc2secret
    spec:
      containers:
      - name: main
        image: registry.redhat.io/openshift4/ose-cli:v4.15
        command:
        - |
          export access_key_id=$(oc get secret logging-loki -ojsonpath='{.data.AWS_ACCESS_KEY_ID}' | base64 -d)
          export access_key_secret=$(oc get secret logging-loki -ojsonpath='{.data.AWS_SECRET_ACCESS_KEY}' | base64 -d)
          export endpoint=$(oc get cm logging-loki -ojsonpath='{.data.BUCKET_HOST}')
          export bucketnames=$(oc get cm logging-loki -ojsonpath='{.data.BUCKET_NAME}')

          oc create secret generic logging-loki-s3 \
            --from-literal=access_key_id=${access_key_id} \
            --from-literal=access_key_secret=${access_key_secret} \
            --from-literal=bucketnames=${bucketnames} \
            --from-literal=endpoint=https://${endpoint} \
            --from-literal=region=japan

      restartPolicy: OnFailure    
