apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: logging-loki 
  namespace: openshift-logging 
spec:
  rules:
    enabled: true
    namespaceSelector:
      matchLabels:
        example.jp/alert: 'true'
    selector:
      matchLabels:
        example.jp/system: hub
  size:	1x.demo
  storage:
    schemas:
    - version: v12
      effectiveDate: "2022-06-01"
    secret:
      name: logging-loki-s3 
      type: s3 
    tls:
      caKey: openshift-service-ca.crt
      caName: service-ca.crt
  storageClassName: gp3-csi
  tenants:
    mode: openshift-logging 
